version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: kunduz
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: kunduz
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
