# Generated by Django 5.0.7 on 2024-07-12 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cve',
            name='last_modified_date',
            field=models.DateField(default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cve',
            name='published_date',
            field=models.DateField(default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cve',
            name='cve_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
